# Core Hugo configuration
title: "Jiaqing Li"
baseURL: "/"

defaultContentLanguage: en
hasCJKLanguage: false
defaultContentLanguageInSubdir: false
removePathAccents: true

build:
  writeStats: true
enableGitInfo: false
summaryLength: 36
pagination:
  pagerSize: 10
enableEmoji: true
enableRobotsTXT: true
footnotereturnlinkcontents: <sup>^</sup>
ignoreFiles: [".ipynb_checkpoints$", "\\.Rmd$", "\\.Rmarkdown$", "_cache$"]
disableAliases: true

outputs:
  home: [HTML, RSS, headers, redirects]
  section: [HTML, RSS]

imaging:
  resampleFilter: lanczos
  quality: 92
  anchor: smart
  hint: picture

timeout: 600000

taxonomies:
  tag: tags
  category: categories
  author: authors

markup:
  _merge: deep
  highlight:
    lineNos: false

security:
  _merge: deep

sitemap:
  _merge: deep
