main:
  - name: About
    url: /
    weight: 10
  - name: Publications
    url: /publications/
    weight: 20
  - name: Projects
    url: /projects/
    weight: 30
  - name: News
    url: /news/
    weight: 40
  - name: Experiences
    url: /experiences/
    weight: 50

footer:
  - name: Explore
    weight: 10
  - parent: Explore
    name: About
    url: /
    weight: 10
  - parent: Explore
    name: Publications
    url: /publications/
    weight: 20
  - parent: Explore
    name: Projects
    url: /projects/
    weight: 30
  - parent: Explore
    name: News
    url: /news/
    weight: 40
  - parent: Explore
    name: Experiences
    url: /experiences/
    weight: 50

  - name: Connect
    weight: 20
  - parent: Connect
    name: Email
    url: mailto:2023210914@stu.hit.edu.cn
    weight: 10
  - parent: Connect
    name: GitHub
    url: https://github.com/lijiaqing1234
    weight: 20
